#!/bin/bash

# Runn a canary deployment by creating a second Deployment for the
# new image and adjusting the number of replicas accordingly.
canary::run() {
  echo "Running a canary deployment"

  local deployment=$(readopt -d --deployment)
  if [ -z "${deployment}" ]; then
    echo "ERROR: canary - No deployment provided with --deployment"
    exit 1
  fi

  local image=$(readopt -i --image)
  if [ -z "${image}" ]; then
    echo "ERROR: canarr - No new image given --image"
    exit 1
  fi

  # Fetch old deployment and check error
  local old_deploy=$(get_deployment "$deployment")
  check_error $old_deploy

  # Create a new deployment descriptor
  local new_deploy=$(new_canary_deployment "$old_deploy" "$image")
  check_error $new_deploy

  # Apply deployment descriptor
  local result=$(apply "$new_deploy")
  check_error $result

  echo "=== Successfully deployed canary $image for $deployment"
}

# Description (used in "-h")
canary::description() {
  echo "Deploy a canary version of the application"
}

# Specific usage of this script
canary::usage() {
  cat <<EOT
  -d --deployment <name>    Name of deployment for which to perform a canary release (mandatory)
  -i --image <image>        Full image name of the target version, including tag (mandatory)
  -r --replicas <replicas>  Replicas of the *full* deployment (default is to take over the existing
                            replicas
     --ratio <percentage>   How many canaries to run, relative to the absolute number (Default: 5%).
                            At least 1 canary is started though.
EOT
}

# ============================================================

# Get the current deployment
get_deployment() {
  local deployment=${1}

  # TODO, e.g.
  #kubectl get deployment "${deployment}" -o yaml
}

# Take a deployment yaml and replace the image with the new one
new_canary_deployment() {
  local deployment=${1}
  local new_image=${2}

  # TODO: Use sed or something else to update the given deployment
}

apply() {
  local deployment=${1}
  # TODO: Use kubctl to add this deployment
  echo "Applied new deployment for canary release"
}
